spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      default_batch_fetch_size: 1000
    properties:
      hibernate:
      show_sql: true
      format_sql: true
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug
